### PR TITLE
docs(README): add example for error handling

### PR DESCRIPTION
**Pull request by till**
As discussed: octokit/octokit.js#2039

### CODE REVIEW

**Comment by nickfloyd** [comment]
Hey @till, Thanks for this change! ❤️ .  The doc looks good content-wise but has some linting issues. Could you either:
1. Update this to reflect what I mentioned above and push the update to this PR or...
2. Set the fork to give [maintainers write access](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I'd be glad to make the change for you!

**Comment by till** [comment]
> Hey @till, Thanks for this change! ❤️ . The doc looks good content-wise but has some linting issues. Could you either:
> 
> 1. Update this to reflect what I mentioned above and push the update to this PR or...
> 2. Set the fork to give [maintainers write access](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I'd be glad to make the change for you!

Hey @nickfloyd — allow edits from maintainers is already checked (I see it right next to this field). So feel free to change as needed. I don't see the exact issues as prettier doesn't say in the log and because I don't have a local clone. But your help is appreciated. :)

**Comment by nickfloyd** [comment]
Hey @till, unfortunately, I don't have write access to your fork. 

> You don't have write access to the till/request-error.js repository, so you cannot push changes to it.
To obtain write access we will point this codespace at your fork of till/request-error.js, creating that fork if it doesn't exist.

Can you run `npm run lint:fix` from your fork and commit the changes?

**Comment by till** [comment]
I did, committed and squashed. LMK

**Comment by till** [comment]
Btw, any idea what this means? 

image

**Review by nickfloyd — APPROVED** [review]

**Comment by nickfloyd** [comment]
> Btw, any idea what this means?
> 
> image

That is the console message that you'll get when maintainer access is not enabled on a fork.

**Comment by till** [comment]
@nickfloyd no, no, at the right `[x] Allow edits by maintainers` — it was checked all along. Was just curious. Anyway, thanks for merging.

**Pull request merged**
